version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "3180:80"
        volumes:
            - ./deployment/local/docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        links:
            - php-fpm
        depends_on:
            - php-fpm
    php-fpm:
        build: ./deployment/local/docker/php-fpm
        links:
            - postgres
            - postgres_testing
        depends_on:
            - postgres
            - postgres_testing
        volumes:
            - ./:/var/www
    postgres:
        image: postgres:latest
        ports:
            - "54320:5432"
        volumes:
          - ./persistent_data:/var/lib/postgresql
        environment:
          - POSTGRES_USER=root
          - POSTGRES_DB=project
          - POSTGRES_PASSWORD=password

    postgres_testing:
        image: postgres:latest
        ports:
            - "54321:5432"
        environment:
          - POSTGRES_USER=root
          - POSTGRES_DB=project_testing
          - POSTGRES_PASSWORD=password
